#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)


//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                 - Moving Straight with Encoders -                                  *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|* 																																																		*|
|*             This program instructs your robot to move forward and backwards 0.5m at a time         *|
|*						 and repeats until 2.5m																											            *|
\*----------------------------------------------------------------------------------------------------*/


int power = 127;
const int BASETIME = 563;

void drive(int increment, int back_forw){
	motor[rightMotor] = power*back_forw;
	motor[leftMotor] = -power*back_forw;
	wait1Msec(BASETIME*increment);
	}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{


	for(int i = 0; i<6;i++){
		drive(i, -1);
		//drive(i, -1);
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
